### ISSUE TITLE
微信登录授权失败

### ISSUE THREAD

**Issue by chenxinjie1129** [doge1024/MyWeWork#5]
微信授权登录，bundle id 不符合

**Comment by MaxsionLiu** [comment]
大佬 能不能提供砸壳后的app？？

**Comment by doge1024** [comment]
因为跑起来的程序是使用的你自己的bundleid，本质上相当于是另外一个app，所以是不能使用微信授权登陆的。推荐使用手机号登陆。
如非常想使用，可以参考[MonkeyDev更新日志](https://github.com/AloneMonkey/MonkeyDev/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97) `bundle id填aaa使用应用原来的bundle id进行重签`

**Comment by chenxinjie1129** [comment]
我昨天跑你的项目，自己测试了一遍，但是测个人发的红包都没有问题，然后没有测群发的，结果下午年会群发的都抢不了，贼尴尬，哈哈哈。幸好自己微信的也玩了弄了自动，微信上的没漏掉
