### ISSUE TITLE
能不能提供企业微信app

### ISSUE THREAD

**Issue by MaxsionLiu** [doge1024/MyWeWork#6]

**Comment by doge1024** [comment]
砸壳的话，找个越狱手机配合[frida-ios-dump](https://github.com/AloneMonkey/frida-ios-dump)，就可以了。纵观github所以提供“便利”的仓库都不提供“成品”。

**Comment by MaxsionLiu** [comment]
谢谢。。。但是我的手机没越狱。。没越狱手机

**Comment by weixuan19930** [comment]
说的好，首先得有一台越狱的手机
