### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by geilige** [doge1024/MyWeWork#8]
报错如下，不知道是不是今天早上更新了最新xcode有关
Showing All Errors Only
MyWeWork-master/Pods/Target Support Files/Pods-MyWeWorkDylib/Pods-MyWeWorkDylib.release.xcconfig: unable to open file (in target "MyWeWorkDylib" in project "MyWeWork")

**Comment by doge1024** [comment]
刚更新了代码，是使用最新的Xcode编译的，可以重试一下看看
